// Generated by CoffeeScript 1.9.2

/*
 * Testing account bot rules
 */

(function() {
  var BankTransact, flow, match2Result, nools, ruleFilePath, runSecond, session;

  nools = require("nools");

  ruleFilePath = __dirname + "/accbot_rules.nools";

  flow = nools.compile(ruleFilePath);

  BankTransact = flow.getDefined('BankTransact');

  console.log('Rules executed @ ' + ruleFilePath);

  session = flow.getSession();

  session.assert(new BankTransact("coles express"));

  session.on("fire", function(name, rule) {
    return console.log("Rule Fired: " + name + " >> Rule= " + rule);
  });

  session.match(function(err) {
    var jsonval, tarry;
    if (err) {
      return console.error(err.stack);
    } else {
      tarry = session.getFacts();
      console.log(tarry);
      jsonval = tarry[0];
      console.log(jsonval);
      console.log('Category=' + session.category);
      console.log('Bla=' + session.bla);
      return console.log("done");
    }
  }).then(function() {
    return runSecond();
  });

  runSecond = function() {
    session = flow.getSession();
    session.assert(new BankTransact("coles express"));
    session.on("fire", function(name, rule) {
      return console.log("Rule2 Fired: " + name + " >> Rule= " + rule);
    });
    console.log('Going to Match');
    return session.match(function(err2) {
      return match2Result(err2);
    });
  };

  match2Result = function(err2) {
    if (err2) {
      console.log('Error occ');
    } else {
      console.log('Facts2:');
      console.log('done 2');
    }
    return console.log('done 3');
  };

}).call(this);
