// Generated by CoffeeScript 1.9.2

/*
 * New coffeescript file
 */

fs = require('fs')

(function() {
  var logger;

  logger = require('tracer').console({
    transport: function(data) {
      console.log(data.output);
      return fs.open('./AccBotLoader.log', 'a', '0666', function(e, id) {
        return fs.write(id, data.output + "\n", null, 'utf8', function() {
          return fs.close(id, function() {});
        });
      });
    }
  });

  logger.log('Test Log Message');

}).call(this);
