// Generated by CoffeeScript 1.9.2

/*
 * New coffeescript file
 */

(function() {
  var Banks, Sequelize, sequelize, vDirName;

  Sequelize = require('sequelize');

  sequelize = new Sequelize('mysql://budget:manager10@localhost:3306/budgetbuddy');

  vDirName = __dirname;

  Banks = sequelize["import"](vDirName + "\\AccBotModel_Banks");

  Banks.count()
  .then ( function(c) { 
	  console.log(c); 
  });

}).call(this);
