// Generated by CoffeeScript 1.9.2

/*
 * Test array loop callback
 */
var dataArray, mainf;

console.log('Test is Starting...');

dataArray = ['a', 'b', 'c', 'd', 'a', 'b', 'c', 'd', 'a', 'b', 'c', 'd', 'a', 'b', 'c', 'd', 'a', 'b', 'c', 'd', 'a', 'b', 'c', 'd', 'a', 'b', 'c', 'd'];

console.log("" + dataArray);

mainf = function() {
  var i, len, results, vElement;
  results = [];
  for (i = 0, len = dataArray.length; i < len; i++) {
    vElement = dataArray[i];
    results.push(console.log(vElement));
  }
  return results;
};

mainf();

console.log('Reached End of Program.');
