// Generated by CoffeeScript 1.9.2

/*
 * Rules Engine Test with Coffeescript
 */
var RE, RuleEngine, fact, rule;

RuleEngine = require('node-rules');

RE = new RuleEngine;

rule = {
  "condition": function(R) {
    return R.when(this.transactionTotal < 500);
  },
  "consequence": function(R) {
    this.result = false;
    this.reason = "The transaction was blocked as it was less than 500";
    return R.stop();
  }
};

RE.register(rule);

fact = {
  "name": "user4",
  "application": "MOB2",
  "transactionTotal": 400,
  "cardType": "Credit Card"
};

RE.execute(fact, function(CBResult) {
  if (CBResult.result) {
    return console.log("Valid transaction");
  } else {
    return console.log("Blocked Reason:" + CBResult.reason);
  }
});
