// Generated by CoffeeScript 1.9.2

/*
 * New coffeescript file
 */

(function() {
  var bunyan, log, myData;

  bunyan = require('bunyan');

  myData = {
    name: "myapp",
    streams: [
      {
        type: 'rotating-file',
        path: 'C:\\Temp\\rv_prog\\nodejs_dev\\endine\\JSTests\\LOGGER\\test_logger.log',
        period: '1d'
      }
    ]
  };

  myData = {
    a: "a string",
    b: 0,
    c: {
      d: [1, 2, 3],
      e: ["another", "array"]
    },
    f: false
  };

  log = bunyan.createLogger(myData);

  log.info("hi");


  /*
  log = bunyan.createLogger 
  	name: "myapp"
   	streams: [	
   	    type: 'rotating-file'
  	   	path: 'C:\\Temp\\rv_prog\\nodejs_dev\\endine\\JSTests\\LOGGER\\test_logger.log'
  	   	period: '1d'
  	   	count: 3
  	   	]
  
  log.info "hi"
   */

}).call(this);
